
---
- name: Deploy Docker Container
  hosts: all
  gather_facts: true
  tasks:
  
    - name: Pull docker container from docker hub
      shell: "docker pull rahul2331998/gitaction"
    
    - name: Run docker container on system
      shell: "docker run -it -d --name frontend rahul2331998/gitaction" 
