
---
- name: Deploy Docker Container
  hosts: all
  gather_facts: true
  tasks:
  
    - name: Pull docker container from docker hub
      shell: "docker pull rahul2331998/gitaction"
      
    - name: Pull docker container from docker hub
      shell: "docker pull rahul2331998/spe_frontend"
      
    - name: Pull docker container from docker hub
      shell: "docker pull rahul2331998/spe_backend:main-ec2383f"  
    

